step 14: there's another source for name clash problems that we haven't explored yet
Let's upgrade our macro a bit, introducing a non-null check into the `alt`
branch of our `getOrElse` logic.

    q"""
      val $temp = $prefix
      if ($temp.isEmpty) Optional.ensuringNotNull($alt) else $temp.value
    """

This way code like `new Optional(null).getOrElse(null)` that uses nulls
on the right-hand side of the getOrElse operator, can be detected and reported.

  [error] (run-main) java.lang.RuntimeException: argument to Optional.getOrElse can't be null
  java.lang.RuntimeException: argument to Optional.getOrElse can't be null
  	at scala.sys.package$.error(package.scala:27)
  	at Optional$.ensuringNotNull(Macros.scala:17)
  	at Test$.main(Test.scala:5)
  	at Test.main(Test.scala)